apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-4iej
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-4iej
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-4iej
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-4iej
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-4iej
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-uwig-tenant/status-quarkus-io/statusquarkusio-4iej@sha256:24c8ed5d0482a084b0df04ce1a04234582fac06f2e19bd6b658d8ffc089a7988
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
